# Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl

# Read data

In [2]:
data = pd.read_csv('ks-projects-201801.csv')

# Gather succesful projs and df and failing projs

In [3]:
succesfull_proj = data.loc[(data['state'] == 'successful')]
failed_proj = data.loc[(data['state'] == 'failed')]

In [4]:
succesfull_proj

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
5,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,4/1/2016,50000.0,2/26/2016 13:38,52375.00,successful,224,US,52375.00,52375.00,50000.00
6,1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,USD,12/21/2014,1000.0,12/1/2014 18:30,1205.00,successful,16,US,1205.00,1205.00,1000.00
11,100005484,Lisa Lim New CD!,Indie Rock,Music,USD,4/8/2013,12500.0,3/9/2013 6:42,12700.00,successful,100,US,12700.00,12700.00,12500.00
14,1000057089,Tombstone: Old West tabletop game and miniatur...,Tabletop Games,Games,GBP,5/3/2017,5000.0,4/5/2017 19:44,94175.00,successful,761,GB,57763.78,121857.33,6469.73
18,1000070642,Mike Corey's Darkness & Light Album,Music,Music,USD,8/17/2012,250.0,8/2/2012 14:11,250.00,successful,7,US,250.00,250.00,250.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378642,999929142,ÉPOUVANTAILS : 28mm Figurines de jeux pour KIN...,Tabletop Games,Games,EUR,10/31/2017,1000.0,10/4/2017 11:26,1246.00,successful,35,FR,66.72,1452.47,1165.70
378644,999934908,The Manual Bar Blade,Product Design,Design,USD,12/15/2015,3500.0,11/23/2015 7:33,6169.00,successful,120,US,6169.00,6169.00,3500.00
378646,999943841,The Dog Coffee Book,Children's Books,Publishing,USD,11/30/2013,950.0,10/18/2013 21:35,1732.02,successful,31,US,1732.02,1732.02,950.00
378651,999969812,AT THE BEACH,Classical Music,Music,CAD,3/22/2014,5000.0,2/20/2014 1:00,5501.00,successful,78,CA,5019.92,4983.69,4529.81
378652,999971898,Beach Wrestling Documentary,Documentary,Film & Video,NOK,4/28/2015,20000.0,3/29/2015 21:30,21500.00,successful,36,NO,2698.97,2875.83,2675.19

In [5]:
failed_proj

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,10/9/2015,1000.0,8/11/2015 12:12,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,11/1/2017,30000.0,9/2/2017 4:43,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2/26/2013,45000.0,1/12/2013 0:20,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,4/16/2012,5000.0,3/17/2012 3:24,1.0,failed,1,US,1.0,1.0,5000.00
7,1000030581,Chaser Strips. Our Strips make Shots their B*tch!,Drinks,Food,USD,3/17/2016,25000.0,2/1/2016 20:05,453.0,failed,40,US,453.0,453.0,25000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378654,999975836,"Homemade fresh dog food, Cleveland OH",Small Batch,Food,USD,4/19/2017,6500.0,3/20/2017 22:08,154.0,failed,4,US,0.0,154.0,6500.00
378657,999977640,The Tribe,Narrative Film,Film & Video,USD,7/19/2011,1500.0,6/22/2011 3:35,155.0,failed,5,US,155.0,155.0,1500.00
378658,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,8/16/2010,15000.0,7/1/2010 19:40,20.0,failed,1,US,20.0,20.0,15000.00
378659,999987933,BioDefense Education Kit,Technology,Technology,USD,2/13/2016,15000.0,1/13/2016 18:13,200.0,failed,6,US,200.0,200.0,15000.00
378660,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,8/16/2011,2000.0,7/19/2011 9:07,524.0,failed,17,US,524.0,524.0,2000.00

# Dominant categories

In [6]:
failed_proj.groupby(['category','main_category']).count().sort_values('ID',ascending=False)

,,ID,name,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
category,main_category,,,,,,,,,,,,,
Product Design,Design,10718,10718,10718,10718,10718,10718,10718,10718,10718,10718,10718,10718,10718
Documentary,Film & Video,8599,8599,8599,8599,8599,8599,8599,8599,8599,8599,8599,8599,8599
Food,Food,7119,7119,7119,7119,7119,7119,7119,7119,7119,7119,7119,7119,7119
Video Games,Games,6942,6941,6942,6942,6942,6942,6942,6942,6942,6942,6942,6942,6942
Music,Music,6201,6201,6201,6201,6201,6201,6201,6201,6201,6201,6145,6201,6201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Comedy,Music,10,10,10,10,10,10,10,10,10,10,10,10,10
Literary Spaces,Publishing,6,6,6,6,6,6,6,6,6,6,6,6,6
Chiptune,Music,6,6,6,6,6,6,6,6,6,6,6,6,6
Taxidermy,Crafts,5,5,5,5,5,5,5,5,5,5,5,5,5
Letterpress,Publishing,4,4,4,4,4,4,4,4,4,4,4,4,4

In [7]:
succesfull_proj.groupby(['category','main_category']).count().sort_values('ID',ascending=False)

,,ID,name,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
category,main_category,,,,,,,,,,,,,
Product Design,Design,7962,7962,7962,7962,7962,7962,7962,7962,7962,7962,7961,7962,7962
Tabletop Games,Games,7866,7866,7866,7866,7866,7866,7866,7866,7866,7866,7866,7866,7866
Shorts,Film & Video,6673,6673,6673,6673,6673,6673,6673,6673,6673,6673,6673,6673,6673
Music,Music,6432,6432,6432,6432,6432,6432,6432,6432,6432,6432,6340,6432,6432
Documentary,Film & Video,5924,5924,5924,5924,5924,5924,5924,5924,5924,5924,5924,5924,5924
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Embroidery,Crafts,19,19,19,19,19,19,19,19,19,19,19,19,19
Literary Spaces,Publishing,13,13,13,13,13,13,13,13,13,13,13,13,13
Comedy,Music,7,7,7,7,7,7,7,7,7,7,7,7,7
Letterpress,Publishing,6,6,6,6,6,6,6,6,6,6,6,6,6
Taxidermy,Crafts,5,5,5,5,5,5,5,5,5,5,5,5,5